### ISSUE TITLE
Error: util - meanCov sizes are incompatible 

### ISSUE THREAD

**Issue by raghavvs** [ruansp/axbycz_calibration#1]
Arrays have incompatible sizes for this operation.

Error in meanCov (line 33)
    Cov = Cov + diff_vex * diff_vex';

# Complete function:
function [Mean, Cov] = meanCov( X )

N = size(X,3);
Mean = eye(4);
Cov = zeros(6,6);

%% Initial approximation of Mean
sum_se = zeros(4,4);
for i = 1:N
    sum_se = sum_se + logm(X(:,:,i));
end
Mean = expm(1/N*sum_se);

%% Iterative process to calculate the true Mean
diff_se = ones(4,4);
max_num = 100;
tol = 1e-5;
count = 1;
while norm(diff_se,'fro') >= tol && count <= max_num
    diff_se = zeros(4,4);
    for i = 1:N
        diff_se = diff_se + logm((Mean)\X(:,:,i));
    end
    Mean = Mean*expm(1/N * diff_se);
    count = count+1;
end
% disp(['Number of iterations: ', num2str(count)]);

%% Covariance
for i = 1:N
    diff_se = logm(Mean\X(:,:,i));
    diff_vex = [vex(diff_se(1:3,1:3)); diff_se(1:3,4)];
    Cov = Cov + diff_vex * diff_vex';
end
Cov = Cov/N;

%% Check
% meanCovCheck(Mean, Cov, X);
% len = 0.1;
% figure; hold on; axis equal;
% trplot(Mean,'color','r', 'length', len)
% for i = 1:N
%     trplot(X(:,:,i), 'color', 'b', 'length', len)
% end

**Comment by ruansp** [comment]
Could you give an example input for the function that generates this error?

**Comment by raghavvs** [comment]
I was tying to run the main_NAO_simluation.m script. I did not give any additional inputs.

**Comment by ruansp** [comment]
Could you add a breakpoint on this line and print the vector `diff_vex `?

There might be problems on the dependencies. For example, the `vex` function in Line 32 is from `rvctools` package [here](https://petercorke.com/toolboxes/robotics-toolbox/)

**Comment by raghavvs** [comment]
I don't have MATLAB on my laptop so I'll do that tomorrow from the lab and let you know. Regarding vex function, I had that issue earlier, but it is fixed now.

**Comment by raghavvs** [comment]
I have verified and reinstalled `rvctools` package again. 

I ran the main_NAO_simulation.m file again and added a breakpoint and `diff_vex` is printed below: 
```
Num of trials:1
Probabilistic Method 1...
   -0.0000
   -0.5612
   -0.0825
    0.0000
    0.3037
   -0.0000
   -0.7979
   -0.6841
    0.2598

34      Cov = Cov + diff_vex * diff_vex';
```

**Comment by ruansp** [comment]
Basically `diff_vex` should be a 6x1 vector, which I have verified in my machine several times. It is constructed in Line 32:
```
diff_vex = [vex(diff_se(1:3,1:3)); diff_se(1:3,4)];
```
I guess it might still be the problem of the `vex` function, which converts a 3x3 skew-symmetric matrix to the vector form (3x1).

Could you double check the `vex` function (should be the function inside `rvctools/spatial-math` package)? What will it return when you input a 3x3 skew-symmetric matrix?

**Comment by raghavvs** [comment]
The issue is resolved. The vex function was causing the issue, I reinstalled and verified the vex function output and now its output vector dimension is correct. Thank you.
